[package]
name = "srdf"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
iri_s = { path = "../iri_s" }
async-trait = "0.1.68"
hashbag = "0.1.11"
serde = "1.0"
serde_derive = "1.0"

