[package]
name = "shex-rs"
version = "0.0.1"

[workspace]
members = [
    "bag",
    "iri_s",
    "prefix_map",
    "srdf",
    "shex_ast",
    # "shex_antlr",
    "shex_pest",
    "srdf_oxgraph",
    "srdf_sparql",
    "shex_testsuite",
    "shex_validation",
    "shapemap",
    "shapemap_oxgraph",
    "validation_oxgraph"
]

default-members = [
    "bag",
    "iri_s",
    "prefix_map",
    "srdf",
    "shex_ast",
    "shex_pest",
    "srdf_oxgraph",
    "srdf_sparql",
    "shex_testsuite",
    "shex_validation",
    "shapemap",
    "shapemap_oxgraph",
    "validation_oxgraph"
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Jose Emilio Labra Gayo <labra@uniovi.es>"]
description = "Rust implementation of ShEx"
repository = "https://github.com/weso/shex_rs"
readme = "./README.md"
keywords = ["rdf", "linked-data", "semantic-web", "shex"] 
documentation = "https://weso.es/shex_rs"
categories = ["rdf"]

[workspace.dependencies]
bag = { version = "0.0.1", path = "./bag" }
iri_s = { version = "0.0.1", path = "./iri_s" }
prefix_map = { version = "0.0.1", path = "./prefix_map" }
srdf = { version = "0.0.1", path = "./srdf" }
srdf_oxgraph = { version = "0.0.1", path = "./srdf_oxgraph" }
srdf_sparql = { version = "0.0.1", path = "./srdf_sparql" }
shex_ast = { version = "0.0.1", path = "./shex_ast" }
shex_antlr = { version = "0.0.1", path = "./shex_antlr" }
shex_testsuite = { version = "0.0.1", path = "./shex_testsuite" }
shex_validation = { version = "0.0.1", path = "./shex_validation" }
shapemap = { version = "0.0.1", path = "./shapemap" }
shapemap_oxgraph = { version = "0.0.1", path = "./shapemap_oxgraph" }
validation_oxgraph = { version = "0.0.1", path = "./validation_oxgraph" }