[package]
name = "shex-rs"
version = "0.0.6"
description = "ShEx implementation in Rust"
license = "GPL-3.0-or-later"
authors = [ 
    "Jose Emilio Labra Gayo",
    "Ángel Iglesias Préstamo <angel.iglesias.prestamo@gmail.com>", 
]
repository = "https://github.com/weso/shapes-rs"
homepage = "https://www.weso.es/shapes-rs/"


[[bin]]
path = "sx_cli/src/main.rs"
name = "sx"  

[workspace]
members = [
    "rbe",
    "rbe_testsuite",
    "iri_s",
    "prefixmap",
    "srdf",
    "shex_ast",
    "shex_compact",
    "sx_cli",
    "srdf_graph",
    "srdf_sparql",
    "shex_testsuite",
    "shex_validation",
    "shapemap",
    "shacl_ast",
    # "shapemap_oxgraph",
    # "validation_oxgraph"
    # "shex_antlr",
    # "shex_pest",
]

#default-members = [
#    "sx_cli"
#]

[workspace.package]
# version = "0.0.6"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Jose Emilio Labra Gayo <labra@uniovi.es>",
    "Ángel Iglesias Préstamo <angel.iglesias.prestamo@gmail.com>", 
]
description = "RDF data shapes implementation in Rust"
repository = "https://github.com/weso/shapes_rs"
homepage = "https://www.weso.es/shapes-rs/"

readme = "./README.md"
keywords = ["rdf", "linked-data", "semantic-web", "shex"] 
categories = ["rdf"]

[workspace.dependencies]
rbe = { version = "0.0.6", path = "./rbe" }
rbe_testsuite = { version = "0.0.6", path = "./rbe_testsuite" }
iri_s = { version = "0.0.6", path = "./iri_s" }
prefixmap = { version = "0.0.6", path = "./prefixmap" }
srdf = { version = "0.0.6", path = "./srdf" }
srdf_graph = { version = "0.0.6", path = "./srdf_graph" }
srdf_sparql = { version = "0.0.6", path = "./srdf_sparql" }
shex_ast = { version = "0.0.6", path = "./shex_ast" }
shex_testsuite = { version = "0.0.6", path = "./shex_testsuite" }
shex_validation = { version = "0.0.6", path = "./shex_validation" }
shex_compact = { version = "0.0.6", path = "./shex_compact" }
shapemap = { version = "0.0.6", path = "./shapemap" }
shacl_ast = { version = "0.0.6", path = "./shacl_ast" }


[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
anyhow = "1.0"
shex_ast = { path = "./shex_ast" }
shex_validation = { path = "./shex_validation" }
shex_compact = { path = "./shex_compact" }
prefixmap = { path = "./prefixmap" }
shapemap = { path = "./shapemap" }
srdf = { path = "./srdf" }
srdf_graph = { path = "./srdf_graph" }
srdf_sparql = { path = "./srdf_sparql" }
iri_s = { path = "./iri_s" }
shacl_ast = { path = "./shacl_ast" }
oxrdf = "0.1.6"
serde_json = "1.0"
regex = "1"
