[package]
name = "shapes-rs"
version = "0.0.12"
description = "RDF Data shapes implementation in Rust"
license = "MIT OR Apache-2.0"
authors = [
    "Jose Emilio Labra Gayo <labra@uniovi.es>",
    "Ángel Iglesias Préstamo <angel.iglesias.prestamo@gmail.com>",
    "Marc-Antoine Arnaud <marc-antoine.arnaud@luminvent.com>",
]
repository = "https://github.com/weso/shapes-rs"
homepage = "https://www.weso.es/shapes-rs/"


[[bin]]
path = "rdfsx_cli/src/main.rs"
name = "rdfsx"

[workspace]
members = [
    "dctap",
    "rbe",
    "rbe_testsuite",
    "iri_s",
    "prefixmap",
    "srdf",
    "shex_ast",
    "shex_compact",
    "rdfsx_cli",
    "shex_testsuite",
    "shex_validation",
    "shapemap",
    "shacl_ast",
    "shapes_converter",
    # "shapemap_oxgraph",
    # "validation_oxgraph"
    # "shex_antlr",
    # "shex_pest",
]
exclude = [
    "shex_compact_winnow"
]

#default-members = [
#    "sx_cli"
#]

[workspace.package]
# version = "0.0.6"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = [
    "Jose Emilio Labra Gayo <labra@uniovi.es>",
    "Ángel Iglesias Préstamo <angel.iglesias.prestamo@gmail.com>",
    "Marc-Antoine Arnaud <marc-antoine.arnaud@luminvent.com>",
]
description = "RDF data shapes implementation in Rust"
repository = "https://github.com/weso/shapes-rs"
homepage = "https://www.weso.es/shapes-rs/"

readme = "./README.md"
keywords = ["rdf", "linked-data", "semantic-web", "shex"]
categories = ["rdf"]

[workspace.dependencies]
rbe = { version = "0.0.12", path = "./rbe" }
rbe_testsuite = { version = "0.0.12", path = "./rbe_testsuite" }
iri_s = { version = "0.0.12", path = "./iri_s" }
prefixmap = { version = "0.0.12", path = "./prefixmap" }
srdf = { version = "0.0.12", path = "./srdf" }
dctap = { version = "0.0.12", path = "./dctap" }
shex_ast = { version = "0.0.12", path = "./shex_ast" }
shex_testsuite = { version = "0.0.12", path = "./shex_testsuite" }
shex_validation = { version = "0.0.12", path = "./shex_validation" }
shex_compact = { version = "0.0.12", path = "./shex_compact" }
shapemap = { version = "0.0.12", path = "./shapemap" }
shacl_ast = { version = "0.0.12", path = "./shacl_ast" }
shaper_converter = { version = "0.0.12", path = "./shapes_converter" }

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
anyhow = "1.0"
shapes_converter = { path = "./shapes_converter" }
shex_ast = { path = "./shex_ast" }
shex_validation = { path = "./shex_validation" }
shex_compact = { path = "./shex_compact" }
prefixmap = { path = "./prefixmap" }
shapemap = { path = "./shapemap" }
srdf = { path = "./srdf" }
iri_s = { path = "./iri_s" }
shacl_ast = { path = "./shacl_ast" }
dctap = { path = "./dctap" }
oxrdf = "0.2.0-alpha.2"
serde_json = "1.0"
regex = "1.10.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }
