[package]
name = "shex-rs"
version = "0.0.1"

[workspace]
members = [
    "iri_s",
    "prefix_map",
    "srdf",
    "shex_ast",
    # "shex_antlr",
    "shex_pest",
    "srdf_oxgraph",
    "shex_testsuite",
    "shex_validation"
]

default-members = [
    "iri_s",
    "prefix_map",
    "srdf",
    "shex_ast",
    "shex_pest",
    "srdf_oxgraph",
    "shex_testsuite",
    "shex_validation"
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Jose Emilio Labra Gayo <labra@uniovi.es>"]
description = "Rust implementation of ShEx"
repository = "https://github.com/weso/shex_rs"
readme = "./README.md"
keywords = ["rdf", "linked-data", "semantic-web", "shex"] 
documentation = "https://weso.es/shex_rs"
categories = ["rdf"]

[workspace.dependencies]
iri_s = { version = "0.0.1", path = "./iri_s" }
prefix_map = { version = "0.0.1", path = "./prefix_map" }
srdf = { version = "0.0.1", path = "./srdf" }
srdf_oxgraph = { version = "0.0.1", path = "./srdf_oxgraph" }
shex_ast = { version = "0.0.1", path = "./shex_ast" }
shex_antlr = { version = "0.0.1", path = "./shex_antlr" }
shex_testsuite = { version = "0.0.1", path = "./shex_testsuite" }
shex_validation = { version = "0.0.1", path = "./shex_validation" }


