[package]
name = "shex-rs"
version = "0.0.2"

[[bin]]
path = "sx/src/main.rs" # shex-cli --> CLI_PATH
name = "sx" # sx --> BINARY_NAME

[workspace]
members = [
    "rbe",
    "rbe_testsuite",
    "iri_s",
    "prefixmap",
    "srdf",
    "shex_ast",
    "shex_compact",
    "shex_cli",
    "srdf_graph",
    "srdf_sparql",
    "shex_testsuite",
    "shex_validation",
    "shapemap",
    "shapemap_oxgraph",
    "validation_oxgraph"
    # "shex_antlr",
    # "shex_pest",
]

#default-members = [
#    "shex_cli"
#]

[workspace.package]
version = "0.0.2"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Jose Emilio Labra Gayo <labra@uniovi.es>"]
description = "Rust implementation of ShEx"
repository = "https://github.com/weso/shex_rs"
readme = "./README.md"
keywords = ["rdf", "linked-data", "semantic-web", "shex"] 
documentation = "https://weso.es/shex_rs"
categories = ["rdf"]

[workspace.dependencies]
rbe = { version = "0.0.1", path = "./rbe" }
rbe_testsuite = { version = "0.0.1", path = "./rbe_testsuite" }
iri_s = { version = "0.0.1", path = "./iri_s" }
prefixmap = { version = "0.0.1", path = "./prefixmap" }
srdf = { version = "0.0.1", path = "./srdf" }
srdf_graph = { version = "0.0.1", path = "./srdf_graph" }
srdf_sparql = { version = "0.0.1", path = "./srdf_sparql" }
shex_ast = { version = "0.0.1", path = "./shex_ast" }
# shex_antlr = { version = "0.0.1", path = "./shex_antlr" }
shex_testsuite = { version = "0.0.1", path = "./shex_testsuite" }
shex_validation = { version = "0.0.1", path = "./shex_validation" }
shapemap = { version = "0.0.1", path = "./shapemap" }
shapemap_oxgraph = { version = "0.0.1", path = "./shapemap_oxgraph" }
validation_oxgraph = { version = "0.0.1", path = "./validation_oxgraph" }

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
anyhow = "1.0"
shex_ast = { path = "./shex_ast" }
shex_validation = { path = "./shex_validation" }
srdf = { path = "./srdf" }
srdf_graph = { path = "./srdf_graph" }
iri_s = { path = "./iri_s" }
oxrdf = "0.1.6"
serde_json = "1.0"
regex = "1"
