[package]
name = "shapemap_oxgraph"
version.workspace = true
authors.workspace = true
documentation = "https://docs.rs/shapemap_oxgraph"
edition.workspace = true


[dependencies]
shapemap = { path = "../shapemap" }
oxrdf = "0.1.7"
thiserror = "1.0"



