[package]
name = "srdf_rio"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true


[dependencies]
rio_api = "0.8.2"
rio_turtle = "0.8.2"
oxrdf = "0.1.5"
srdf = { path = "../srdf" }

