[package]
name = "srdf_rio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rio_api = "0.8.2"
rio_turtle = "0.8.2"
srdf = { path = "../srdf" }

