[package]
name = "rbe"
version = "0.0.10"
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
documentation = "https://docs.rs/rbe"
homepage.workspace = true
repository.workspace = true

[dependencies]
thiserror = "1"
hashbag = { version = "0.1.11"}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.9"
itertools = "0.12"
log = "0.4"
env_logger = "0.11"
indexmap = { version = "2"}

[dev-dependencies]
test-log = "0.2.12"
indoc = "2"
