[package]
name = "dctap"
version = "0.1.0"
authors.workspace = true
description.workspace = true
documentation = "https://docs.rs/dctap"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
csv = "1.3.0"
indexmap = { version = "2"}
itertools = "0.13"
serde = "1.0"
serde_derive = "1.0"
serde_with = "3.8.1"
thiserror = "1"
tracing = "0.1"
