[package]
name = "shex_compact_winnow"
version = "0.0.10"
authors.workspace = true
description.workspace = true
documentation = "https://docs.rs/shex_compact"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
shex_ast = { path = "../shex_ast", version = "0.0.10" }
rbe = { path = "../rbe", version = "0.0.10" }
iri_s = { path = "../iri_s", version = "0.0.10" }
srdf = { path = "../srdf", version = "0.0.10" }
prefixmap = { path = "../prefixmap", version = "0.0.10" } 
shapemap = { path = "../shapemap", version = "0.0.10" } 
thiserror = "1"
colored = "2"
rust_decimal = "1.32"
rust_decimal_macros = "1.32"
pretty = "0.12.3"
winnow = "0.5.37"

[dev-dependencies]
criterion = "0.5"
pprof = { version = "0.13.0", features = ["criterion", "flamegraph"] }

