[package]
name = "shex_ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
srdf = { path = "../srdf" }
iri_s = { path = "../iri_s" }
prefix_map = { path = "../prefix_map" }
