[package]
name = "shex_ast"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true


[dependencies]
srdf = { path = "../srdf" }
iri_s = { path = "../iri_s" }
rbe = { path = "../rbe" }
prefix_map = { path = "../prefix_map" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
void = "1"
thiserror = "1.0"
log = "0.4"
lazy_static = "1"

[dev-dependencies]
env_logger = "0.10"
test-log = "0.2.12"
