[package]
name = "shex_ast"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true


[dependencies]
srdf = { path = "../srdf", version = "0.0.2" }
iri_s = { path = "../iri_s", version = "0.0.2" }
rbe = { path = "../rbe", version = "0.0.2" }
prefixmap = { path = "../prefixmap", version = "0.0.2" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
void = "1"
thiserror = "1.0"
log = "0.4"
lazy_static = "1"
rust_decimal = "1.32"
rust_decimal_macros = "1.32"

[dev-dependencies]
env_logger = "0.10"
test-log = "0.2.12"
