[package]
name = "shex_validation"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
async-recursion = "1.0.4"
iri_s = { path = "../iri_s" }
srdf = { path = "../srdf" }
shex_ast = { path = "../shex_ast" }
shapemap = { path = "../shapemap" }
thiserror = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
srdf_graph = { path = "../srdf_graph" }
shapemap_oxgraph = { path = "../shapemap_oxgraph" }
oxrdf = "0.1.6"

