[package]
name = "shex_validation"
version = "0.0.14"
authors.workspace = true
description.workspace = true
documentation = "https://docs.rs/shex_validation"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
iri_s = { path = "../iri_s", version = "0.0.13" }
rbe = { path = "../rbe", version = "0.0.13" }
srdf = { path = "../srdf", version = "0.0.14" }
shex_ast = { path = "../shex_ast", version = "0.0.14" }
shapemap = { path = "../shapemap", version = "0.0.14" }
prefixmap = { path = "../prefixmap", version = "0.0.13" }
async-recursion = "1.0.4"
thiserror = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = { version = "^1.35", features = ["full"] }
tracing = "0.1"
indexmap = { version = "2" }
colored = "2"
either = "1"

[dev-dependencies]
oxrdf = "0.2.0-alpha.2"
