[package]
name = "shex_validation"
version = "0.0.5"
authors.workspace = true
description.workspace = true
documentation = "https://docs.rs/shex_validation"
edition.workspace = true
license.workspace = true

[dependencies]
iri_s = { path = "../iri_s", version = "0.0.5" }
rbe = { path = "../rbe", version = "0.0.5" }
srdf = { path = "../srdf", version = "0.0.5" }
shex_ast = { path = "../shex_ast", version = "0.0.5" }
shapemap = { path = "../shapemap", version = "0.0.5" }
prefixmap = { path = "../prefixmap", version = "0.0.5" }
async-recursion = "1.0.4"
thiserror = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.10"
indexmap = { version = "2", feature = "serde" }


[dev-dependencies]
srdf_graph = { path = "../srdf_graph", version = "0.0.4" }
oxrdf = "0.1.6"

