[package]
name = "rbe_testsuite"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rbe = { path = "../rbe" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.9"
anyhow = "1.0.27"

[dev-dependencies]
indoc = "2"

