[package]
name = "rbe_testsuite"
version = "0.0.13"
authors.workspace = true
description.workspace = true
documentation = "https://docs.rs/rbe_testsuite"
edition.workspace = true
license.workspace = true

[dependencies]
rbe = { path = "../rbe", version = "0.0.13" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.9"
anyhow = "1.0.27"
tracing = "0.1"

[dev-dependencies]
indoc = "2"
