[package]
name = "iri_s"
version = "0.0.5"
authors.workspace = true
description.workspace = true
documentation = "https://docs.rs/iri_s"
edition.workspace = true
license.workspace = true

[dependencies]
oxrdf = "0.1.6"
oxiri = "0.2.2"
thiserror = "1.0.0"
serde = "1.0"
serde_derive = "1.0"
lazy_static = "1"
