[package]
name = "iri_s"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
oxrdf = "0.1.6"
thiserror = "1.0.0"
serde = "1.0"
serde_derive = "1.0"
