[package]
name = "shex_testsuite"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
shex_ast = { path = "../shex_ast" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
void = "1"
clap = { version = "4.2.1", features = ["derive"] }
