[package]
name = "shex_compact"
version = "0.1.0"
authors.workspace = true
description.workspace = true
documentation = "https://docs.rs/shex_compact"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
shex_ast = { path = "../shex_ast", version = "0.1.0" }
rbe = { path = "../rbe", version = "0.0.13" }
iri_s = { path = "../iri_s", version = "0.0.13" }
srdf = { path = "../srdf", version = "0.1.0" }
prefixmap = { path = "../prefixmap", version = "0.1.0" } 
shapemap = { path = "../shapemap", version = "0.1.0" } 
nom = "7"
nom-regex = "0.2"
nom_locate = "4"
regex = "1.10.3"
thiserror = "1"
tracing = "0.1"
colored = "2"
rust_decimal = "1.32"
rust_decimal_macros = "1.32"
pretty = "0.12.3"
lazy-regex = "3.1"

[dev-dependencies]
criterion = "0.5"
tracing-subscriber = "0.3"
pprof = { version = "0.13.0", features = ["criterion", "flamegraph"] }

[[bench]]
name = "shex_parse"
harness = false

[[bench]]
name = "shex_compact_simple"
harness = false

[[bench]]
name = "regex"
harness = false
