[package]
name = "shex_compact"
version = "0.0.2"
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
shex_ast = { path = "../shex_ast", version = "0.0.2" }
iri_s = { path = "../iri_s", version = "0.0.2" }
prefixmap = { path = "../prefixmap", version = "0.0.2" } 
nom = "7"
thiserror = "1"
