[package]
name = "shex_compact"
version = "0.0.3"
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
shex_ast = { path = "../shex_ast", version = "0.0.3" }
rbe = { path = "../rbe", version = "0.0.3" }
iri_s = { path = "../iri_s", version = "0.0.3" }
srdf = { path = "../srdf", version = "0.0.3" }
prefixmap = { path = "../prefixmap", version = "0.0.3" } 
nom = "7"
nom_locate = "4"
thiserror = "1"
log = "0.4"
colored = "2"
rust_decimal = "1.32"
rust_decimal_macros = "1.32"
pretty-print = "0.1.9"

[dev-dependencies]
env_logger = "0.10"

