[package]
<<<<<<< HEAD
name = "rdfsx"
version = "0.1.0"
=======
name = "pyshapes"
version = "0.1.7"
>>>>>>> 3bb845ff0bab894cfdc3727646f92deb54d48253
documentation = "https://www.weso.es/shapes-rs/"
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true

[lib]
name = "rdfsx"
crate-type = ["cdylib"]

[dependencies]
srdf = { workspace = true }
shacl_ast = { workspace = true }
openssl = { version = "0.10.57", features = ["vendored"] }

[dependencies.pyo3]
version = "0.22.0"
features = ["abi3-py37"]
