[package]
name = "prefix_map"
version = "0.0.2"
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true 

[dependencies]
iri_s = { path = "../iri_s" }
indexmap = "1.9.2"
colored = "2"
