[package]
name = "prefix_map"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true 

[dependencies]
iri_s = { version = "0.0.1", path = "../iri_s" }
indexmap = "1.9.2"
colored = "2"
