[package]
name = "prefix_map"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true 

[dependencies]
indexmap = "1.9.2"
iri_s = { path = "../iri_s" }

