[package]
name = "shacl_ast"
version = "0.0.11"
authors.workspace = true
description.workspace = true
documentation = "https://docs.rs/shacl_ast"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
srdf = { path = "../srdf", version = "0.0.11" }
iri_s = { path = "../iri_s", version = "0.0.11" }
rbe = { path = "../rbe", version = "0.0.11" }
prefixmap = { path = "../prefixmap", version = "0.0.11" }
serde = "1"
serde_derive = "1"
void = "1"
thiserror = "1.0"
lazy_static = "1"
rust_decimal = "1.32"
rust_decimal_macros = "1.32"
regex = "1.10"
serde_json = "1"
const_format = "0.2"
itertools = "0.13"

[dev-dependencies]
