[package]
name = "shex_antlr"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
shex_ast = { path = "../shex_ast" }
antlr-rust = { version = "0.3.0-beta" }
