name: Artifacts

on:
  push:
    branches:
      - main
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  binary_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: rustup update
      - uses: Swatinem/rust-cache@v2
      - run: Remove-Item -LiteralPath "C:\msys64\" -Force -Recurse
      - run: cargo build --release
        working-directory: ./shex_cli
      - uses: actions/upload-artifact@v3
        with:
          name: shex_cli
          path: target/release/shex_cli.exe
      - run: mv target/release/shex_cli.exe chec_cli_${{ github.event.release.tag_name }}.exe
        if: github.event_name == 'release'
      - uses: softprops/action-gh-release@v1
        with:
          files: shex_cli_${{ github.event.release.tag_name }}.exe
        if: github.event_name == 'release'
