[package]
name = "validation_oxgraph"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true


[dependencies]
shex_ast = { path = "../shex_ast" }
shapemap_oxgraph = { path = "../shapemap_oxgraph" }
shapemap = { path = "../shapemap" }
oxrdf = "0.1.6"
thiserror = "1.0"



