[package]
name = "validation_oxgraph"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation = "https://docs.rs/validation_oxgraph"
edition.workspace = true


[dependencies]
srdf = { path = "../srdf" }
shex_ast = { path = "../shex_ast" }
shapemap_oxgraph = { path = "../shapemap_oxgraph" }
shapemap = { path = "../shapemap" }
oxrdf = "0.1.6"
thiserror = "1.0"

[dev-dependencies]
serde = "1.0"
serde_json = "1.0"



